Updated feeds for Lisboa, Portugal
MobilityData/mobility-database-catalogs pull request #259
Opened 2023-03-15 18:20 UTC by joao-vasconcelos

Hello, with this PR:

- Direct Download URL for feed Carris Metropolitana has been updated ([pt-lisboa-carris-metropolitana-gtfs-1900.json](https://github.com/MobilityData/mobility-database-catalogs/commit/4749cc91a0f207c54d11d227fdbbc03709247a4a#diff-7449931ad12bbacc6d3ec2e270960f0ccd3401bbdf8ac78a3a83b4d58edd7f9b));
- Previous Carris Metropolitana feeds have been marked as `inactive`, since they are no longer intended to be used directly;
- Old operators feeds have been marked as `inactive` since they are no longer valid;
- The `inactive` feeds have been deleted. I don't know if they should deleted or kept on forever as inactive.

Thank you!

2023-03-15 18:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MobilityData/mobility-database-catalogs?pullRequest=259) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MobilityData/mobility-database-catalogs?pullRequest=259) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MobilityData/mobility-database-catalogs?pullRequest=259) it.</sub>

2023-03-15 18:29 UTC, emmambd requested changes
Hi @joao-vasconcelos! Thanks for this correction and submission. Are you using the Mobility Database at Carris Metropolitana? 

A few minor suggestions: 

- You can set the feeds that shouldn't be used from `inactive` to `deprecated` since they have been replaced. We only use inactive when a replacement has not been provided by an operator.
- Can you add the deprecated feeds back to your PR? We have to preserve the numerical IDs of the feeds for our tests. In the future when we include historical feeds, we'll just swap out the feed links and move the old URL into a different field.

2023-03-16 01:14 UTC, joao-vasconcelos commented
Hey @emmambd! I've made new commits with your corrections.

We are a young company and we recently published our GTFS. It is the first time that the Lisbon metropolitan area can get schedules and network information in a single unified place, or get it at all. We'd like it to be everywhere : ) We have been using [Transit Land](https://www.transit.land/operators/o-eyck-carris#map) to visualize the network, but I don't know if this is related with Mobility Data.

Thank you!

2023-03-16 14:01 UTC, emmambd approved these changes
@joao-vasconcelos That's great to hear! Very happy you're publishing GTFS and made sure to update the Mobility Database with your aggregated feed. 🎉 Thanks for making these changes. Transit Land is a separate GTFS platform, but it's great you're using the tools out there to do visualizations.

2023-03-16 14:04 UTC, merged